manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: CreepyShadow
      url-base: https://github.com/tCreepyShadow
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
#    - name: zmk-config-lotus58-ble
#      remote: CreepyShadow
#      revision: main
    - name: lotus58-ble-zmk
      remote: CreepyShadow
      revision: main
#    - name: lotus58_ble-zmk-config
#      remote: CreepyShadow
#      revision: main
    - name: zmk-helpers
      remote: urob
      revision: main
  self:
    path: config
